name: fos-markirovka
base: core24
#title: Bitrix24 Cloud Cash Machine
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
version: '2024.09.20'
summary: 1OS.Markirovka # 79 char long summary
description: This app connect your Thermal printer to Bitrix24
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon: ./icon.png

apps:    
  fos-markirovka:
    command: run.sh
    extensions:
      - gnome
    common-id: fos-markirovka
    environment:
      PATH: $PATH:$SNAP/
    plugs: [home, network, cups, desktop]
  lpinfo:
    command: usr/sbin/lpinfo
    plugs: [network, cups]
  lpadmin:
    command: usr/sbin/lpadmin
    plugs: [network, avahi-observe, home, cups]
  lpstat:
    command: usr/bin/lpstat
    plugs: [network, avahi-observe, cups]
  lpoptions:
    command: usr/bin/lpoptions
    plugs: [network, home, cups]
  lp:
    command: usr/bin/lp
    plugs: [network, home, cups]
  cancel:
    command: usr/bin/cancel
    plugs: [network, cups]
  lpmove:
    command: usr/sbin/lpmove
    plugs: [network, cups]
  cupsenable:
    command: usr/sbin/cupsenable
    plugs: [network, cups]
  cupsdisable:
    command: usr/sbin/cupsdisable
    plugs: [network, cups]
  cupsaccept:
    command: usr/sbin/cupsaccept
    plugs: [network, cups]
  cupsreject:
    command: usr/sbin/cupsreject
    plugs: [network, cups]
  accept:
    command: usr/sbin/cupsaccept
    plugs: [network, cups]
  reject:
    command: usr/sbin/cupsreject
    plugs: [network, cups]
  cupsctl:
    command: usr/sbin/cupsctl
    plugs: [network, cups]

parts:
  assets:
    source: assets/
    plugin: dump
  libs:
    plugin: dump
    source: .
    after: [assets]
    override-build: |
      dotnet publish fos.markirovka.csproj --configuration Release --self-contained -o ${CRAFT_PART_INSTALL}
    build-packages: 
      - dotnet-sdk-8.0
    stage-packages:
      - libnotify-bin
  cups-client:
    plugin: dump
    source: .
    stage-packages:
        - cups-client
        - libcups2
    prime:
        - usr/bin/*
        - usr/sbin/*
        - usr/lib/*
  
